# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ImageReverse.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QProgressBar,
    QPushButton, QScrollArea, QSizePolicy, QTextEdit,
    QTreeWidget, QTreeWidgetItem, QWidget)
import resources.resources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setEnabled(True)
        Form.resize(1097, 600)
        Form.setMinimumSize(QSize(1097, 600))
        Form.setMaximumSize(QSize(1097, 600))
        icon = QIcon()
        icon.addFile(u":/picture/icon.ico", QSize(), QIcon.Normal, QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupPath = QGroupBox(Form)
        self.groupPath.setObjectName(u"groupPath")
        self.groupPath.setGeometry(QRect(6, 0, 270, 70))
        self.inputImgPath = QLineEdit(self.groupPath)
        self.inputImgPath.setObjectName(u"inputImgPath")
        self.inputImgPath.setGeometry(QRect(6, 14, 196, 22))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputImgPath.sizePolicy().hasHeightForWidth())
        self.inputImgPath.setSizePolicy(sizePolicy)
        self.btnImgPath = QPushButton(self.groupPath)
        self.btnImgPath.setObjectName(u"btnImgPath")
        self.btnImgPath.setGeometry(QRect(205, 13, 60, 24))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.btnImgPath.sizePolicy().hasHeightForWidth())
        self.btnImgPath.setSizePolicy(sizePolicy1)
        self.btnImgPath.setMinimumSize(QSize(0, 0))
        self.btnImgPath.setAutoFillBackground(False)
        self.btnImgPath.setAutoDefault(False)
        self.btnImgPath.setFlat(False)
        self.inputSavePath = QLineEdit(self.groupPath)
        self.inputSavePath.setObjectName(u"inputSavePath")
        self.inputSavePath.setEnabled(True)
        self.inputSavePath.setGeometry(QRect(6, 40, 196, 22))
        self.btnSavePath = QPushButton(self.groupPath)
        self.btnSavePath.setObjectName(u"btnSavePath")
        self.btnSavePath.setGeometry(QRect(205, 39, 60, 24))
        sizePolicy1.setHeightForWidth(self.btnSavePath.sizePolicy().hasHeightForWidth())
        self.btnSavePath.setSizePolicy(sizePolicy1)
        self.btnSavePath.setMinimumSize(QSize(0, 0))
        self.btnSavePath.setAutoFillBackground(False)
        self.btnSavePath.setAutoDefault(False)
        self.btnSavePath.setFlat(False)
        self.groupListImg = QGroupBox(Form)
        self.groupListImg.setObjectName(u"groupListImg")
        self.groupListImg.setGeometry(QRect(282, 280, 270, 316))
        self.listImgTree = QTreeWidget(self.groupListImg)
        self.listImgTree.setObjectName(u"listImgTree")
        self.listImgTree.setGeometry(QRect(6, 14, 258, 296))
        self.listImgTree.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.groupProgress = QGroupBox(Form)
        self.groupProgress.setObjectName(u"groupProgress")
        self.groupProgress.setGeometry(QRect(6, 70, 270, 136))
        self.btnChangeStructure = QPushButton(self.groupProgress)
        self.btnChangeStructure.setObjectName(u"btnChangeStructure")
        self.btnChangeStructure.setEnabled(True)
        self.btnChangeStructure.setGeometry(QRect(5, 44, 260, 24))
        self.btnChangeStructure.setAutoDefault(False)
        self.btnChangeStructure.setFlat(False)
        self.btnImgReverse = QPushButton(self.groupProgress)
        self.btnImgReverse.setObjectName(u"btnImgReverse")
        self.btnImgReverse.setEnabled(True)
        self.btnImgReverse.setGeometry(QRect(5, 74, 260, 24))
        self.btnImgReverse.setAutoDefault(False)
        self.btnImgReverse.setFlat(False)
        self.btnReadImg = QPushButton(self.groupProgress)
        self.btnReadImg.setObjectName(u"btnReadImg")
        self.btnReadImg.setEnabled(True)
        self.btnReadImg.setGeometry(QRect(5, 14, 260, 24))
        self.btnReadImg.setAutoDefault(False)
        self.btnReadImg.setFlat(False)
        self.barProgress = QProgressBar(self.groupProgress)
        self.barProgress.setObjectName(u"barProgress")
        self.barProgress.setEnabled(True)
        self.barProgress.setGeometry(QRect(6, 105, 258, 22))
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.barProgress.sizePolicy().hasHeightForWidth())
        self.barProgress.setSizePolicy(sizePolicy2)
        self.barProgress.setValue(0)
        self.barProgress.setAlignment(Qt.AlignCenter)
        self.barProgress.setTextVisible(True)
        self.groupImgBig = QGroupBox(Form)
        self.groupImgBig.setObjectName(u"groupImgBig")
        self.groupImgBig.setGeometry(QRect(282, 0, 270, 280))
        self.scrollAreaImgBig = QScrollArea(self.groupImgBig)
        self.scrollAreaImgBig.setObjectName(u"scrollAreaImgBig")
        self.scrollAreaImgBig.setGeometry(QRect(6, 14, 258, 258))
        self.scrollAreaImgBig.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollAreaImgBig.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollAreaImgBig.setWidgetResizable(True)
        self.scrollAreaImgBigWidget = QWidget()
        self.scrollAreaImgBigWidget.setObjectName(u"scrollAreaImgBigWidget")
        self.scrollAreaImgBigWidget.setGeometry(QRect(0, 0, 256, 256))
        self.labelImgBigShow = QLabel(self.scrollAreaImgBigWidget)
        self.labelImgBigShow.setObjectName(u"labelImgBigShow")
        self.labelImgBigShow.setGeometry(QRect(0, 0, 258, 258))
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.labelImgBigShow.sizePolicy().hasHeightForWidth())
        self.labelImgBigShow.setSizePolicy(sizePolicy3)
        self.labelImgBigShow.setMinimumSize(QSize(50, 50))
        self.labelImgBigShow.setMaximumSize(QSize(9999, 9999))
        self.labelImgBigShow.setFrameShape(QFrame.NoFrame)
        self.labelImgBigShow.setAlignment(Qt.AlignCenter)
        self.labelImgBigBack = QLabel(self.scrollAreaImgBigWidget)
        self.labelImgBigBack.setObjectName(u"labelImgBigBack")
        self.labelImgBigBack.setGeometry(QRect(0, 0, 258, 258))
        sizePolicy3.setHeightForWidth(self.labelImgBigBack.sizePolicy().hasHeightForWidth())
        self.labelImgBigBack.setSizePolicy(sizePolicy3)
        self.labelImgBigBack.setMinimumSize(QSize(50, 50))
        self.labelImgBigBack.setMaximumSize(QSize(9999, 9999))
        self.labelImgBigBack.setAlignment(Qt.AlignCenter)
        self.labelImgBigText = QLabel(self.scrollAreaImgBigWidget)
        self.labelImgBigText.setObjectName(u"labelImgBigText")
        self.labelImgBigText.setGeometry(QRect(0, 0, 258, 258))
        sizePolicy3.setHeightForWidth(self.labelImgBigText.sizePolicy().hasHeightForWidth())
        self.labelImgBigText.setSizePolicy(sizePolicy3)
        self.labelImgBigText.setAlignment(Qt.AlignBottom|Qt.AlignRight|Qt.AlignTrailing)
        self.labelImgBigText.setMargin(2)
        self.scrollAreaImgBig.setWidget(self.scrollAreaImgBigWidget)
        self.labelImgBigBack.raise_()
        self.labelImgBigShow.raise_()
        self.labelImgBigText.raise_()
        self.groupMessage = QGroupBox(Form)
        self.groupMessage.setObjectName(u"groupMessage")
        self.groupMessage.setGeometry(QRect(6, 206, 270, 390))
        self.inputMessage = QTextEdit(self.groupMessage)
        self.inputMessage.setObjectName(u"inputMessage")
        self.inputMessage.setGeometry(QRect(6, 14, 258, 370))
        self.inputMessage.setReadOnly(True)
        self.inputMessage.setTextInteractionFlags(Qt.NoTextInteraction)
        self.groupImgSmall = QGroupBox(Form)
        self.groupImgSmall.setObjectName(u"groupImgSmall")
        self.groupImgSmall.setGeometry(QRect(557, 0, 535, 596))
        self.scrollAreaImgSmall = QScrollArea(self.groupImgSmall)
        self.scrollAreaImgSmall.setObjectName(u"scrollAreaImgSmall")
        self.scrollAreaImgSmall.setGeometry(QRect(6, 14, 523, 576))
        self.scrollAreaImgSmall.setFrameShadow(QFrame.Plain)
        self.scrollAreaImgSmall.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollAreaImgSmall.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollAreaImgSmall.setWidgetResizable(False)
        self.scrollAreaImgSmallWidget = QWidget()
        self.scrollAreaImgSmallWidget.setObjectName(u"scrollAreaImgSmallWidget")
        self.scrollAreaImgSmallWidget.setGeometry(QRect(0, 0, 505, 574))
        self.scrollAreaImgSmallWidget.setMaximumSize(QSize(512, 16777215))
        self.labelImgSmallBack = QLabel(self.scrollAreaImgSmallWidget)
        self.labelImgSmallBack.setObjectName(u"labelImgSmallBack")
        self.labelImgSmallBack.setGeometry(QRect(-1, -1, 505, 576))
        sizePolicy3.setHeightForWidth(self.labelImgSmallBack.sizePolicy().hasHeightForWidth())
        self.labelImgSmallBack.setSizePolicy(sizePolicy3)
        self.labelImgSmallBack.setFrameShape(QFrame.StyledPanel)
        self.labelImgSmallBack.setAlignment(Qt.AlignCenter)
        self.scrollAreaImgSmall.setWidget(self.scrollAreaImgSmallWidget)

        self.retranslateUi(Form)

        self.btnImgPath.setDefault(False)
        self.btnSavePath.setDefault(False)
        self.btnChangeStructure.setDefault(False)
        self.btnImgReverse.setDefault(False)
        self.btnReadImg.setDefault(False)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u5e8f\u5217\u5e27\u56fe\u7247\u7ffb\u8f6c\u5de5\u5177", None))
        self.groupPath.setTitle(QCoreApplication.translate("Form", u"\u8def\u5f84\u9009\u62e9", None))
        self.btnImgPath.setText(QCoreApplication.translate("Form", u"\u7d20\u6750\u8def\u5f84", None))
        self.btnSavePath.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58\u4f4d\u7f6e", None))
        self.groupListImg.setTitle(QCoreApplication.translate("Form", u"\u56fe\u7247\u5217\u8868", None))
        ___qtreewidgetitem = self.listImgTree.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("Form", u"\u8def\u5f84", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("Form", u"\u540d\u79f0", None));
        self.groupProgress.setTitle(QCoreApplication.translate("Form", u"\u56fe\u7247\u64cd\u4f5c", None))
        self.btnChangeStructure.setText(QCoreApplication.translate("Form", u"\u8c03\u6574\u7ed3\u6784", None))
        self.btnImgReverse.setText(QCoreApplication.translate("Form", u"\u7ffb\u8f6c\u56fe\u7247", None))
        self.btnReadImg.setText(QCoreApplication.translate("Form", u"\u8bfb\u53d6\u56fe\u7247", None))
        self.barProgress.setFormat(QCoreApplication.translate("Form", u"%p%", None))
        self.groupImgBig.setTitle(QCoreApplication.translate("Form", u"\u5927\u56fe\u9884\u89c8", None))
        self.labelImgBigShow.setText("")
        self.labelImgBigBack.setText("")
        self.labelImgBigText.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb\u62d6\u52a8\u56fe\u7247\uff0c\u4f7f\u7528\u6eda\u8f6e\u7f29\u653e", None))
        self.groupMessage.setTitle(QCoreApplication.translate("Form", u"\u6d88\u606f\u8f93\u51fa", None))
        self.inputMessage.setHtml(QCoreApplication.translate("Form", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.groupImgSmall.setTitle(QCoreApplication.translate("Form", u"\u5c0f\u56fe\u9884\u89c8", None))
        self.labelImgSmallBack.setText("")
    # retranslateUi

