# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ImageReverse.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QProgressBar,
    QPushButton, QSizePolicy, QTextEdit, QTreeWidget,
    QTreeWidgetItem, QWidget)
import resources.resources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setEnabled(True)
        Form.resize(1000, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(1000, 600))
        Form.setMaximumSize(QSize(1000, 600))
        icon = QIcon()
        icon.addFile(u":/picture/icon.ico", QSize(), QIcon.Normal, QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupPath = QGroupBox(Form)
        self.groupPath.setObjectName(u"groupPath")
        self.groupPath.setGeometry(QRect(10, 0, 271, 91))
        self.horizontalLayoutWidget = QWidget(self.groupPath)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 20, 251, 31))
        self.ImgPath = QHBoxLayout(self.horizontalLayoutWidget)
        self.ImgPath.setSpacing(2)
        self.ImgPath.setObjectName(u"ImgPath")
        self.ImgPath.setContentsMargins(0, 0, 0, 0)
        self.inputImgPath = QLineEdit(self.horizontalLayoutWidget)
        self.inputImgPath.setObjectName(u"inputImgPath")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.inputImgPath.sizePolicy().hasHeightForWidth())
        self.inputImgPath.setSizePolicy(sizePolicy1)

        self.ImgPath.addWidget(self.inputImgPath)

        self.btnImgPath = QPushButton(self.horizontalLayoutWidget)
        self.btnImgPath.setObjectName(u"btnImgPath")
        sizePolicy.setHeightForWidth(self.btnImgPath.sizePolicy().hasHeightForWidth())
        self.btnImgPath.setSizePolicy(sizePolicy)
        self.btnImgPath.setMinimumSize(QSize(0, 0))
        self.btnImgPath.setAutoFillBackground(False)
        self.btnImgPath.setAutoDefault(False)
        self.btnImgPath.setFlat(False)

        self.ImgPath.addWidget(self.btnImgPath)

        self.layoutWidget = QWidget(self.groupPath)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 50, 251, 31))
        self.SavePath = QHBoxLayout(self.layoutWidget)
        self.SavePath.setSpacing(2)
        self.SavePath.setObjectName(u"SavePath")
        self.SavePath.setContentsMargins(0, 0, 0, 0)
        self.inputSavePath = QLineEdit(self.layoutWidget)
        self.inputSavePath.setObjectName(u"inputSavePath")
        self.inputSavePath.setEnabled(True)

        self.SavePath.addWidget(self.inputSavePath)

        self.btnSavePath = QPushButton(self.layoutWidget)
        self.btnSavePath.setObjectName(u"btnSavePath")
        sizePolicy.setHeightForWidth(self.btnSavePath.sizePolicy().hasHeightForWidth())
        self.btnSavePath.setSizePolicy(sizePolicy)
        self.btnSavePath.setMinimumSize(QSize(0, 0))
        self.btnSavePath.setAutoFillBackground(False)
        self.btnSavePath.setAutoDefault(False)
        self.btnSavePath.setFlat(False)

        self.SavePath.addWidget(self.btnSavePath)

        self.groupListImg = QGroupBox(Form)
        self.groupListImg.setObjectName(u"groupListImg")
        self.groupListImg.setGeometry(QRect(290, 280, 271, 311))
        self.listImgTree = QTreeWidget(self.groupListImg)
        self.listImgTree.setObjectName(u"listImgTree")
        self.listImgTree.setGeometry(QRect(10, 20, 251, 281))
        self.groupProgress = QGroupBox(Form)
        self.groupProgress.setObjectName(u"groupProgress")
        self.groupProgress.setGeometry(QRect(10, 90, 271, 141))
        self.btnChangeStructure = QPushButton(self.groupProgress)
        self.btnChangeStructure.setObjectName(u"btnChangeStructure")
        self.btnChangeStructure.setEnabled(True)
        self.btnChangeStructure.setGeometry(QRect(10, 50, 251, 23))
        self.btnChangeStructure.setAutoDefault(False)
        self.btnChangeStructure.setFlat(False)
        self.btnImageReverse = QPushButton(self.groupProgress)
        self.btnImageReverse.setObjectName(u"btnImageReverse")
        self.btnImageReverse.setEnabled(True)
        self.btnImageReverse.setGeometry(QRect(10, 80, 251, 23))
        self.btnImageReverse.setAutoDefault(False)
        self.btnImageReverse.setFlat(False)
        self.btnReadImg = QPushButton(self.groupProgress)
        self.btnReadImg.setObjectName(u"btnReadImg")
        self.btnReadImg.setEnabled(True)
        self.btnReadImg.setGeometry(QRect(10, 20, 251, 23))
        self.btnReadImg.setAutoDefault(False)
        self.btnReadImg.setFlat(False)
        self.barProgress = QProgressBar(self.groupProgress)
        self.barProgress.setObjectName(u"barProgress")
        self.barProgress.setEnabled(True)
        self.barProgress.setGeometry(QRect(10, 110, 251, 21))
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.barProgress.sizePolicy().hasHeightForWidth())
        self.barProgress.setSizePolicy(sizePolicy2)
        self.barProgress.setValue(0)
        self.barProgress.setAlignment(Qt.AlignCenter)
        self.barProgress.setTextVisible(True)
        self.groupImgBig = QGroupBox(Form)
        self.groupImgBig.setObjectName(u"groupImgBig")
        self.groupImgBig.setGeometry(QRect(290, 0, 271, 281))
        self.labelImgBig1 = QLabel(self.groupImgBig)
        self.labelImgBig1.setObjectName(u"labelImgBig1")
        self.labelImgBig1.setGeometry(QRect(10, 20, 251, 251))
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.labelImgBig1.sizePolicy().hasHeightForWidth())
        self.labelImgBig1.setSizePolicy(sizePolicy3)
        self.labelImgBig1.setMinimumSize(QSize(50, 50))
        self.labelImgBig1.setMaximumSize(QSize(9999, 9999))
        self.labelImgBig1.setFrameShape(QFrame.Panel)
        self.labelImgBig1.setFrameShadow(QFrame.Sunken)
        self.labelImgBig1.setAlignment(Qt.AlignCenter)
        self.groupMessage = QGroupBox(Form)
        self.groupMessage.setObjectName(u"groupMessage")
        self.groupMessage.setGeometry(QRect(10, 230, 271, 361))
        self.inputMessage = QTextEdit(self.groupMessage)
        self.inputMessage.setObjectName(u"inputMessage")
        self.inputMessage.setGeometry(QRect(10, 20, 251, 331))
        self.inputMessage.setReadOnly(True)
        self.groupImgSmall = QGroupBox(Form)
        self.groupImgSmall.setObjectName(u"groupImgSmall")
        self.groupImgSmall.setGeometry(QRect(570, 10, 421, 581))
        self.labelImgSmall_1 = QLabel(self.groupImgSmall)
        self.labelImgSmall_1.setObjectName(u"labelImgSmall_1")
        self.labelImgSmall_1.setGeometry(QRect(10, 20, 50, 50))
        sizePolicy3.setHeightForWidth(self.labelImgSmall_1.sizePolicy().hasHeightForWidth())
        self.labelImgSmall_1.setSizePolicy(sizePolicy3)
        self.labelImgSmall_1.setMinimumSize(QSize(50, 50))
        self.labelImgSmall_1.setMaximumSize(QSize(50, 50))
        self.labelImgSmall_1.setFrameShape(QFrame.Panel)
        self.labelImgSmall_1.setFrameShadow(QFrame.Sunken)
        self.labelImgSmall_1.setAlignment(Qt.AlignCenter)
        self.labelImgSmall_2 = QLabel(self.groupImgSmall)
        self.labelImgSmall_2.setObjectName(u"labelImgSmall_2")
        self.labelImgSmall_2.setGeometry(QRect(60, 20, 50, 50))
        sizePolicy3.setHeightForWidth(self.labelImgSmall_2.sizePolicy().hasHeightForWidth())
        self.labelImgSmall_2.setSizePolicy(sizePolicy3)
        self.labelImgSmall_2.setMinimumSize(QSize(50, 50))
        self.labelImgSmall_2.setMaximumSize(QSize(50, 50))
        self.labelImgSmall_2.setFrameShape(QFrame.Panel)
        self.labelImgSmall_2.setFrameShadow(QFrame.Sunken)
        self.labelImgSmall_2.setAlignment(Qt.AlignCenter)
        self.labelImgSmall_3 = QLabel(self.groupImgSmall)
        self.labelImgSmall_3.setObjectName(u"labelImgSmall_3")
        self.labelImgSmall_3.setGeometry(QRect(110, 20, 50, 50))
        sizePolicy3.setHeightForWidth(self.labelImgSmall_3.sizePolicy().hasHeightForWidth())
        self.labelImgSmall_3.setSizePolicy(sizePolicy3)
        self.labelImgSmall_3.setMinimumSize(QSize(50, 50))
        self.labelImgSmall_3.setMaximumSize(QSize(50, 50))
        self.labelImgSmall_3.setFrameShape(QFrame.Panel)
        self.labelImgSmall_3.setFrameShadow(QFrame.Sunken)
        self.labelImgSmall_3.setAlignment(Qt.AlignCenter)
        self.labelImgSmall_4 = QLabel(self.groupImgSmall)
        self.labelImgSmall_4.setObjectName(u"labelImgSmall_4")
        self.labelImgSmall_4.setGeometry(QRect(160, 20, 50, 50))
        sizePolicy3.setHeightForWidth(self.labelImgSmall_4.sizePolicy().hasHeightForWidth())
        self.labelImgSmall_4.setSizePolicy(sizePolicy3)
        self.labelImgSmall_4.setMinimumSize(QSize(50, 50))
        self.labelImgSmall_4.setMaximumSize(QSize(50, 50))
        self.labelImgSmall_4.setFrameShape(QFrame.Panel)
        self.labelImgSmall_4.setFrameShadow(QFrame.Sunken)
        self.labelImgSmall_4.setAlignment(Qt.AlignCenter)
        self.labelImgSmall_5 = QLabel(self.groupImgSmall)
        self.labelImgSmall_5.setObjectName(u"labelImgSmall_5")
        self.labelImgSmall_5.setGeometry(QRect(210, 20, 50, 50))
        sizePolicy3.setHeightForWidth(self.labelImgSmall_5.sizePolicy().hasHeightForWidth())
        self.labelImgSmall_5.setSizePolicy(sizePolicy3)
        self.labelImgSmall_5.setMinimumSize(QSize(50, 50))
        self.labelImgSmall_5.setMaximumSize(QSize(50, 50))
        self.labelImgSmall_5.setFrameShape(QFrame.Panel)
        self.labelImgSmall_5.setFrameShadow(QFrame.Sunken)
        self.labelImgSmall_5.setAlignment(Qt.AlignCenter)
        self.labelImgSmall_6 = QLabel(self.groupImgSmall)
        self.labelImgSmall_6.setObjectName(u"labelImgSmall_6")
        self.labelImgSmall_6.setGeometry(QRect(260, 20, 50, 50))
        sizePolicy3.setHeightForWidth(self.labelImgSmall_6.sizePolicy().hasHeightForWidth())
        self.labelImgSmall_6.setSizePolicy(sizePolicy3)
        self.labelImgSmall_6.setMinimumSize(QSize(50, 50))
        self.labelImgSmall_6.setMaximumSize(QSize(50, 50))
        self.labelImgSmall_6.setFrameShape(QFrame.Panel)
        self.labelImgSmall_6.setFrameShadow(QFrame.Sunken)
        self.labelImgSmall_6.setAlignment(Qt.AlignCenter)
        self.labelImgSmall_7 = QLabel(self.groupImgSmall)
        self.labelImgSmall_7.setObjectName(u"labelImgSmall_7")
        self.labelImgSmall_7.setGeometry(QRect(310, 20, 50, 50))
        sizePolicy3.setHeightForWidth(self.labelImgSmall_7.sizePolicy().hasHeightForWidth())
        self.labelImgSmall_7.setSizePolicy(sizePolicy3)
        self.labelImgSmall_7.setMinimumSize(QSize(50, 50))
        self.labelImgSmall_7.setMaximumSize(QSize(50, 50))
        self.labelImgSmall_7.setFrameShape(QFrame.Panel)
        self.labelImgSmall_7.setFrameShadow(QFrame.Sunken)
        self.labelImgSmall_7.setAlignment(Qt.AlignCenter)
        self.labelImgSmall_8 = QLabel(self.groupImgSmall)
        self.labelImgSmall_8.setObjectName(u"labelImgSmall_8")
        self.labelImgSmall_8.setGeometry(QRect(360, 20, 50, 50))
        sizePolicy3.setHeightForWidth(self.labelImgSmall_8.sizePolicy().hasHeightForWidth())
        self.labelImgSmall_8.setSizePolicy(sizePolicy3)
        self.labelImgSmall_8.setMinimumSize(QSize(50, 50))
        self.labelImgSmall_8.setMaximumSize(QSize(50, 50))
        self.labelImgSmall_8.setFrameShape(QFrame.Panel)
        self.labelImgSmall_8.setFrameShadow(QFrame.Sunken)
        self.labelImgSmall_8.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Form)

        self.btnImgPath.setDefault(False)
        self.btnSavePath.setDefault(False)
        self.btnChangeStructure.setDefault(False)
        self.btnImageReverse.setDefault(False)
        self.btnReadImg.setDefault(False)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u5e8f\u5217\u5e27\u56fe\u7247\u7ffb\u8f6c\u5de5\u5177", None))
        self.groupPath.setTitle(QCoreApplication.translate("Form", u"\u8def\u5f84\u9009\u62e9", None))
        self.btnImgPath.setText(QCoreApplication.translate("Form", u"\u7d20\u6750\u8def\u5f84", None))
        self.btnSavePath.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58\u4f4d\u7f6e", None))
        self.groupListImg.setTitle(QCoreApplication.translate("Form", u"\u56fe\u7247\u5217\u8868", None))
        ___qtreewidgetitem = self.listImgTree.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("Form", u"\u8def\u5f84", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("Form", u"\u540d\u79f0", None));
        self.groupProgress.setTitle(QCoreApplication.translate("Form", u"\u56fe\u7247\u64cd\u4f5c", None))
        self.btnChangeStructure.setText(QCoreApplication.translate("Form", u"\u8c03\u6574\u7ed3\u6784", None))
        self.btnImageReverse.setText(QCoreApplication.translate("Form", u"\u7ffb\u8f6c\u56fe\u7247", None))
        self.btnReadImg.setText(QCoreApplication.translate("Form", u"\u8bfb\u53d6\u56fe\u7247", None))
        self.barProgress.setFormat(QCoreApplication.translate("Form", u"%p%", None))
        self.groupImgBig.setTitle(QCoreApplication.translate("Form", u"\u5927\u56fe\u9884\u89c8", None))
        self.labelImgBig1.setText("")
        self.groupMessage.setTitle(QCoreApplication.translate("Form", u"\u6d88\u606f\u8f93\u51fa", None))
        self.inputMessage.setHtml(QCoreApplication.translate("Form", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.groupImgSmall.setTitle(QCoreApplication.translate("Form", u"\u5c0f\u56fe\u9884\u89c8", None))
        self.labelImgSmall_1.setText("")
        self.labelImgSmall_2.setText("")
        self.labelImgSmall_3.setText("")
        self.labelImgSmall_4.setText("")
        self.labelImgSmall_5.setText("")
        self.labelImgSmall_6.setText("")
        self.labelImgSmall_7.setText("")
        self.labelImgSmall_8.setText("")
    # retranslateUi

